import type { AppSettings, Trial } from '@/types';

// Generated from the backend's reconciled sample data (sample-data/) so the offline demo shows the
// same records as the API. Regenerate if the sample data or the reconciliation rules change.

/** Default settings, mirroring the backend defaults in demo mode. */
export const DEMO_SETTINGS: AppSettings = {
  display: {
    app_name: 'AgriEvidence',
    organization: '',
    yield_unit: 't/ha',
    decimals: 2,
    table_columns: [
      'id',
      'crop',
      'product',
      'country',
      'year',
      'trial_type',
      'treatment_yield',
      'control_yield',
      'uplift_pct',
      'status',
      'sources',
    ],
  },
  reference_data: {
    crops: [
      {
        name: 'Wheat',
        aliases: [],
      },
      {
        name: 'Potato',
        aliases: ['Potatoes'],
      },
      {
        name: 'Maize',
        aliases: ['Corn'],
      },
      {
        name: 'Rice',
        aliases: [],
      },
      {
        name: 'Barley',
        aliases: [],
      },
      {
        name: 'Rapeseed',
        aliases: ['Canola', 'Oilseed rape'],
      },
    ],
    products: [
      {
        name: 'Harvest Plus',
        aliases: ['HarvestPlus'],
      },
      {
        name: 'Root Boost',
        aliases: ['RootBoost'],
      },
    ],
    countries: [
      {
        name: 'France',
        aliases: [],
        code: 'FR',
      },
      {
        name: 'Germany',
        aliases: ['Deutschland'],
        code: 'DE',
      },
      {
        name: 'Spain',
        aliases: ['España'],
        code: 'ES',
      },
      {
        name: 'Italy',
        aliases: [],
        code: 'IT',
      },
      {
        name: 'Netherlands',
        aliases: ['Holland', 'The Netherlands'],
        code: 'NL',
      },
      {
        name: 'Poland',
        aliases: [],
        code: 'PL',
      },
      {
        name: 'United Kingdom',
        aliases: ['UK', 'Great Britain'],
        code: 'GB',
      },
      {
        name: 'United States',
        aliases: ['USA'],
        code: 'US',
      },
    ],
    trial_types: [
      {
        name: 'Scientific',
        aliases: ['Research'],
        color: 'blue',
        description: 'Designed research trial, usually replicated with statistical analysis.',
      },
      {
        name: 'Demonstration',
        aliases: ['Demo', 'Demo plot'],
        color: 'amber',
        description: 'Showcase plot, often a single site without replication.',
      },
      {
        name: 'Commercial',
        aliases: ['On-farm'],
        color: 'orange',
        description: 'Run on a working farm.',
      },
    ],
    units: [
      {
        unit: 't/ha',
        to_kg_per_ha: 1000.0,
        aliases: ['t ha-1', 't per ha', 'tonnes/ha', 'tonnes per hectare', 'tonne/ha', 'mt/ha'],
      },
      {
        unit: 'kg/ha',
        to_kg_per_ha: 1.0,
        aliases: ['kg ha-1', 'kg per ha', 'kilograms per hectare'],
      },
      {
        unit: 'q/ha',
        to_kg_per_ha: 100.0,
        aliases: ['dt/ha', 'quintal/ha', 'quintals per hectare'],
      },
      {
        unit: 'lb/ac',
        to_kg_per_ha: 1.12085,
        aliases: ['lb/acre', 'lbs/acre', 'pounds per acre'],
      },
    ],
    strict_vocabulary: false,
  },
  custom_fields: {
    fields: [
      {
        key: 'soil_type',
        label: 'Soil type',
        type: 'select',
        options: ['Clay', 'Loam', 'Sandy', 'Silt'],
        unit: null,
        required: false,
        description: 'Dominant soil texture at the trial site.',
        show_in_table: false,
        show_in_filters: true,
        show_in_compare: true,
        chartable: false,
        source_aliases: [],
      },
      {
        key: 'application_rate',
        label: 'Application rate',
        type: 'number',
        options: [],
        unit: 'L/ha',
        required: false,
        description: 'Product dose applied to the treated plots.',
        show_in_table: false,
        show_in_filters: false,
        show_in_compare: true,
        chartable: true,
        source_aliases: [],
      },
    ],
  },
  comparison: {
    max_trials: 6,
    show_yield_chart: true,
    show_uplift_chart: true,
    show_difference_chart: false,
    show_custom_charts: true,
    highlight_differences: true,
    fields: [
      'crop',
      'product',
      'country',
      'year',
      'trial_type',
      'treatment_yield',
      'control_yield',
      'yield_difference',
      'uplift_pct',
      'status',
      'caveats',
      'sources',
    ],
  },
  ingestion: {
    field_aliases: {
      trial_id: ['trial_id', 'trial id', 'trial reference', 'trial ref', 'trial number', 'trial code'],
      crop: ['crop', 'crop name', 'crop type'],
      product: ['product', 'product name', 'treatment product', 'tested product'],
      country: ['country', 'country code', 'country name', 'location', 'site country'],
      year: ['year', 'season year', 'season', 'trial year', 'harvest year'],
      trial_type: ['trial_type', 'trial type', 'trial category', 'type of trial'],
      treatment_yield: ['treatment_yield', 'treatment yield', 'treated yield', 'yield treated', 'treated'],
      control_yield: [
        'control_yield',
        'control yield',
        'untreated yield',
        'untreated control yield',
        'untreated control',
        'yield control',
        'untreated',
        'control',
        'check yield',
      ],
      yield_unit: ['yield_unit', 'yield unit', 'unit', 'units'],
      notes: ['notes', 'note', 'findings', 'comments', 'remarks', 'observations'],
    },
    default_yield_unit: 't/ha',
    use_llm_extraction: true,
  },
  reconciliation: {
    numeric_tolerance_pct: 0.5,
    conflict_strategy: 'source_priority',
    source_priority: ['manual', 'csv', 'report'],
    caveat_rules: [
      {
        label: 'Replication not documented',
        match_all: ['replicat'],
        match_any: [
          'not documented',
          'unavailable',
          'not available',
          'not reported',
          'unknown',
          'unreplicated',
        ],
      },
      {
        label: 'Statistical analysis not documented',
        match_all: ['statistic'],
        match_any: ['not documented', 'unavailable', 'not available', 'not reported', 'unknown'],
      },
      {
        label: 'Single demonstration site',
        match_all: [],
        match_any: ['one demonstration site', 'single site', 'one site'],
      },
    ],
  },
  assistant: {
    enabled: true,
    model: '',
    ollama_base_url: '',
    temperature: 0.1,
    num_ctx: 16384,
    think: false,
    max_tool_iterations: 6,
    max_revisions: 2,
    enable_reflection: true,
    offline_fallback: true,
    force_offline: false,
    history_turns: 6,
    extra_instructions: '',
    suggested_questions: [
      'What is the average yield uplift of Harvest Plus on wheat?',
      'Which trials have conflicting data?',
      'Which product performs best?',
      'Compare T01 and T04',
      'How strong is the evidence for Root Boost on potatoes?',
    ],
  },
  access: {
    allow_self_signup: false,
  },
};

/** The sample trials as the backend reconciles them. */
export const DEMO_TRIALS: readonly Trial[] = [
  {
    id: 'T01',
    crop: 'Wheat',
    product: 'Harvest Plus',
    country: 'France',
    year: 2023,
    trial_type: 'Scientific',
    treatment_yield: 8.4,
    control_yield: 8.0,
    yield_unit: 't/ha',
    yield_difference: 0.4,
    uplift_pct: 5.0,
    uplift_range: null,
    status: 'consistent',
    caveats: [],
    conflicts: [],
    missing_fields: [],
    sources: [
      {
        file: 'trials_a.csv',
        kind: 'csv',
        locator: 'row 2',
        values: {
          crop: 'Wheat',
          product: 'Harvest Plus',
          country: 'France',
          year: '2023',
          trial_type: 'Scientific',
          treatment_yield: '8.4 t/ha',
          control_yield: '8.0 t/ha',
        },
        extraction: 'rules',
      },
      {
        file: 'trials_b.csv',
        kind: 'csv',
        locator: 'row 2',
        values: {
          crop: 'wheat',
          product: 'HarvestPlus',
          country: 'FR',
          year: '2023',
          trial_type: 'scientific',
          treatment_yield: '8400 kg/ha',
          control_yield: '8000 kg/ha',
        },
        extraction: 'rules',
      },
    ],
    notes: [],
    custom_fields: {},
    overridden_fields: [],
    origin: 'ingested',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'T02',
    crop: 'Wheat',
    product: 'Harvest Plus',
    country: 'Germany',
    year: 2024,
    trial_type: 'Demonstration',
    treatment_yield: 7.8,
    control_yield: 7.5,
    yield_unit: 't/ha',
    yield_difference: 0.3,
    uplift_pct: 4.0,
    uplift_range: null,
    status: 'consistent',
    caveats: [
      'Replication not documented',
      'Statistical analysis not documented',
      'Single demonstration site',
    ],
    conflicts: [],
    missing_fields: [],
    sources: [
      {
        file: 'trials_a.csv',
        kind: 'csv',
        locator: 'row 3',
        values: {
          crop: 'wheat',
          product: 'HARVESTPLUS',
          country: 'DE',
          year: '2024',
          trial_type: 'Demonstration',
          treatment_yield: '7800 kg/ha',
          control_yield: '7500 kg/ha',
        },
        extraction: 'rules',
      },
      {
        file: 'T02_field_report.txt',
        kind: 'report',
        locator: 'report',
        values: {
          crop: 'Wheat',
          product: 'HarvestPlus',
          country: 'Germany',
          year: '2024',
          trial_type: 'Demonstration',
          treatment_yield: '7.8 t/ha',
          control_yield: '7.5 t/ha',
        },
        extraction: 'rules',
      },
    ],
    notes: [
      {
        source: 'T02_field_report.txt',
        text: 'One demonstration site. Replication and statistical significance are not documented.',
      },
    ],
    custom_fields: {},
    overridden_fields: [],
    origin: 'ingested',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'T03',
    crop: 'Potato',
    product: 'Root Boost',
    country: 'Spain',
    year: 2023,
    trial_type: 'Demonstration',
    treatment_yield: 42.0,
    control_yield: 40.0,
    yield_unit: 't/ha',
    yield_difference: 2.0,
    uplift_pct: 5.0,
    uplift_range: [5.0, 10.0],
    status: 'conflict',
    caveats: ['Conflicting treated yield between sources'],
    conflicts: [
      {
        field: 'treatment_yield',
        label: 'Treated yield',
        status: 'open',
        candidates: [
          {
            value: 42.0,
            display: '42 t/ha',
            sources: ['trials_a.csv'],
          },
          {
            value: 44.0,
            display: '44 t/ha',
            sources: ['T03_summary.txt'],
          },
        ],
        chosen_display: '42 t/ha',
        resolved_by: null,
        note: '',
      },
    ],
    missing_fields: [],
    sources: [
      {
        file: 'trials_a.csv',
        kind: 'csv',
        locator: 'row 4',
        values: {
          crop: 'Potato',
          product: 'Root Boost',
          country: 'Spain',
          year: '2023',
          trial_type: 'Demonstration',
          treatment_yield: '42 t/ha',
          control_yield: '40 t/ha',
        },
        extraction: 'rules',
      },
      {
        file: 'T03_summary.txt',
        kind: 'report',
        locator: 'report',
        values: {
          crop: 'Potato',
          product: 'RootBoost',
          country: 'Spain',
          year: '2023',
          trial_type: 'Demonstration',
          treatment_yield: '44 t/ha',
          control_yield: '40 t/ha',
        },
        extraction: 'rules',
      },
    ],
    notes: [
      {
        source: 'T03_summary.txt',
        text: 'This report and the spreadsheet give different treated yields. Neither source indicates which result is final.',
      },
    ],
    custom_fields: {},
    overridden_fields: [],
    origin: 'ingested',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'T04',
    crop: 'Potato',
    product: 'Root Boost',
    country: 'France',
    year: 2024,
    trial_type: 'Scientific',
    treatment_yield: 45.0,
    control_yield: 45.0,
    yield_unit: 't/ha',
    yield_difference: 0.0,
    uplift_pct: 0.0,
    uplift_range: null,
    status: 'consistent',
    caveats: ['Replication not documented', 'Statistical analysis not documented'],
    conflicts: [],
    missing_fields: [],
    sources: [
      {
        file: 'trials_b.csv',
        kind: 'csv',
        locator: 'row 3',
        values: {
          crop: 'potatoes',
          product: 'ROOTBOOST',
          country: 'FR',
          year: '2024',
          trial_type: 'scientific',
          treatment_yield: '45000 kg/ha',
          control_yield: '45000 kg/ha',
        },
        extraction: 'rules',
      },
      {
        file: 'T04_scientific_report.txt',
        kind: 'report',
        locator: 'report',
        values: {
          crop: 'Potatoes',
          product: 'Root Boost',
          country: 'France',
          year: '2024',
          trial_type: 'Scientific',
          treatment_yield: '45 t/ha',
          control_yield: '45 t/ha',
        },
        extraction: 'rules',
      },
    ],
    notes: [
      {
        source: 'T04_scientific_report.txt',
        text: 'The recorded yields are equal. Replication details and statistical analysis are unavailable in this extract.',
      },
    ],
    custom_fields: {},
    overridden_fields: [],
    origin: 'ingested',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'T05',
    crop: 'Wheat',
    product: 'Harvest Plus',
    country: 'Germany',
    year: 2025,
    trial_type: 'Demonstration',
    treatment_yield: 8.1,
    control_yield: null,
    yield_unit: 't/ha',
    yield_difference: null,
    uplift_pct: null,
    uplift_range: null,
    status: 'incomplete',
    caveats: ['Control yield missing – uplift cannot be calculated', 'Reported by a single source'],
    conflicts: [],
    missing_fields: ['control_yield'],
    sources: [
      {
        file: 'trials_b.csv',
        kind: 'csv',
        locator: 'row 4',
        values: {
          crop: 'WHEAT',
          product: 'Harvest Plus',
          country: 'DE',
          year: '2025',
          trial_type: 'demonstration',
          treatment_yield: '8100 kg/ha',
        },
        extraction: 'rules',
      },
    ],
    notes: [],
    custom_fields: {},
    overridden_fields: [],
    origin: 'ingested',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'T06',
    crop: 'Wheat',
    product: 'Harvest Plus',
    country: 'Spain',
    year: 2021,
    trial_type: 'Scientific',
    treatment_yield: 6.6,
    control_yield: 6.0,
    yield_unit: 't/ha',
    yield_difference: 0.6,
    uplift_pct: 10.0,
    uplift_range: null,
    status: 'single_source',
    caveats: [
      'Reported by a single source',
      'Replication not documented',
      'Statistical analysis not documented',
    ],
    conflicts: [],
    missing_fields: [],
    sources: [
      {
        file: 'T06_archive_note.txt',
        kind: 'report',
        locator: 'report',
        values: {
          crop: 'Wheat',
          product: 'Harvest Plus',
          country: 'Spain',
          year: '2021',
          trial_type: 'Scientific',
          treatment_yield: '6.6 t/ha',
          control_yield: '6.0 t/ha',
        },
        extraction: 'rules',
      },
    ],
    notes: [
      {
        source: 'T06_archive_note.txt',
        text: 'This trial appears only in the archive note. Replication details and statistical analysis are unavailable in this extract.',
      },
    ],
    custom_fields: {},
    overridden_fields: [],
    origin: 'ingested',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
];
