import { Cpu, PlugZap } from 'lucide-react';
import { useEffect, useId, useState } from 'react';
import { Badge, Button, Card, FormField, Notice, Select, TextArea, TextInput, Toggle } from '@/components/ui';
import { useAsyncResource, useChatStore, useSettingsSection } from '@/hooks';
import type { AssistantMode, LlmTestResult } from '@/types';
import { api, errorMessage } from '@/utils';
import { AgentLoopDiagram } from '../AgentLoopDiagram';
import { SaveBar } from '../SaveBar';

const MODE_BADGES: Record<AssistantMode, { tone: 'emerald' | 'amber' | 'red' | 'neutral'; label: string }> = {
  llm: { tone: 'emerald', label: 'LLM answering' },
  offline: { tone: 'amber', label: 'Offline planner' },
  unavailable: { tone: 'red', label: 'Unavailable' },
  disabled: { tone: 'neutral', label: 'Switched off' },
};

const StatusCard = ({ model, ollamaBaseUrl }: { model: string; ollamaBaseUrl: string }) => {
  const status = useChatStore((state) => state.status);
  const loadStatus = useChatStore((state) => state.loadStatus);
  const [test, setTest] = useState<LlmTestResult | null>(null);
  const [testError, setTestError] = useState<string | null>(null);
  const [isTesting, setIsTesting] = useState(false);

  useEffect(() => {
    void loadStatus();
  }, [loadStatus]);

  const runTest = async () => {
    setIsTesting(true);
    setTest(null);
    setTestError(null);
    try {
      setTest(await api.assistant.test(model, ollamaBaseUrl));
      await loadStatus();
    } catch (error) {
      setTestError(errorMessage(error));
    } finally {
      setIsTesting(false);
    }
  };

  const installed = Array.isArray(status?.ollama?.available_models)
    ? (status.ollama.available_models as string[])
    : [];

  return (
    <Card
      title="Status"
      description="The assistant runs in the separate LLM service (LangGraph + Ollama). Without the model, the same graph answers with the rule-based planner."
      actions={
        <Button size="sm" variant="outline" onClick={() => void runTest()} disabled={isTesting}>
          <PlugZap size={15} aria-hidden="true" /> {isTesting ? 'Testing…' : 'Test the model'}
        </Button>
      }
    >
      {status ? (
        <div className="space-y-3 text-sm">
          <p className="flex flex-wrap items-center gap-2">
            <Badge tone={MODE_BADGES[status.mode].tone}>{MODE_BADGES[status.mode].label}</Badge>
            {status.model && (
              <span className="inline-flex items-center gap-1 font-mono text-stone-700">
                <Cpu size={14} aria-hidden="true" /> {status.model}
              </span>
            )}
          </p>
          <p className="text-stone-600">{status.detail}</p>
          <dl className="grid grid-cols-1 gap-2 text-xs sm:grid-cols-2">
            <div>
              <dt className="font-semibold text-stone-500">LLM service</dt>
              <dd className="font-mono text-stone-700">{status.service_url}</dd>
            </div>
            <div>
              <dt className="font-semibold text-stone-500">Models installed in Ollama</dt>
              <dd className="font-mono text-stone-700">
                {installed.length ? installed.join(', ') : 'none found'}
              </dd>
            </div>
          </dl>
        </div>
      ) : (
        <p className="text-sm text-stone-500">Checking the LLM service…</p>
      )}
      {test && (
        <Notice
          tone={test.ok ? 'success' : 'warning'}
          className="mt-4"
          title={test.ok ? 'The model answered' : 'The model did not answer'}
        >
          {test.ok
            ? `${test.model} replied “${test.reply}” in ${((test.latency_ms ?? 0) / 1000).toFixed(1)} s.`
            : (test.error ?? 'Unknown error.')}
        </Notice>
      )}
      {testError && (
        <Notice tone="error" className="mt-4">
          {testError}
        </Notice>
      )}
    </Card>
  );
};

const GraphSource = () => {
  const { data, error } = useAsyncResource(api.assistant.graph);
  if (error)
    return <p className="text-xs text-stone-500">The graph source is available when the LLM service runs.</p>;
  if (!data) return null;
  return (
    <details className="mt-3 text-xs">
      <summary className="cursor-pointer text-stone-600">Mermaid source generated by LangGraph</summary>
      <pre className="mt-2 max-h-72 overflow-auto rounded-lg bg-stone-50 p-3 font-mono text-[11px] text-stone-700">
        {data.agent}
      </pre>
      <pre className="mt-2 max-h-48 overflow-auto rounded-lg bg-stone-50 p-3 font-mono text-[11px] text-stone-700">
        {data.extraction}
      </pre>
    </details>
  );
};

export const AssistantSection = () => {
  const ids = useId();
  const section = useSettingsSection('assistant');
  const assistant = section.draft;
  const defaults = useChatStore((state) => state.status?.service_defaults);
  const defaultModel = typeof defaults?.model === 'string' ? defaults.model : 'qwen3.6';

  return (
    <>
      <StatusCard model={assistant.model} ollamaBaseUrl={assistant.ollama_base_url} />

      <Card
        title="Model and loops"
        footer={
          <SaveBar
            isDirty={section.isDirty}
            isSaving={section.isSaving}
            error={section.error}
            message={section.message}
            onSave={() => void section.save()}
            onDiscard={section.discard}
            onReset={() => void section.resetToDefaults()}
          />
        }
        bodyClassName="space-y-6"
      >
        <Toggle
          label="Assistant enabled"
          description="When off, the chat tells users the assistant is switched off."
          checked={assistant.enabled}
          onChange={(enabled) => section.update({ enabled })}
        />
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <FormField
            id={`${ids}-model`}
            label="Ollama model"
            hint="qwen3.6 (35B-A3B, ~24 GB RAM) or qwen3.6:27b (~17 GB). Leave empty for the LLM service's default."
          >
            <TextInput
              id={`${ids}-model`}
              value={assistant.model}
              placeholder={`service default: ${defaultModel}`}
              className="font-mono"
              onChange={(event) => section.update({ model: event.target.value.trim() })}
            />
          </FormField>
          <FormField
            id={`${ids}-url`}
            label="Ollama address"
            hint="Point this at a GPU machine if this computer is too small. Empty = service default."
          >
            <TextInput
              id={`${ids}-url`}
              value={assistant.ollama_base_url}
              placeholder="http://127.0.0.1:11434"
              className="font-mono"
              onChange={(event) => section.update({ ollama_base_url: event.target.value.trim() })}
            />
          </FormField>
          <FormField id={`${ids}-temperature`} label="Temperature" hint="Low values keep answers factual.">
            <TextInput
              id={`${ids}-temperature`}
              type="number"
              min={0}
              max={2}
              step="0.1"
              value={String(assistant.temperature)}
              onChange={(event) => section.update({ temperature: Number(event.target.value) })}
            />
          </FormField>
          <FormField id={`${ids}-ctx`} label="Context window (tokens)">
            <Select
              id={`${ids}-ctx`}
              value={String(assistant.num_ctx)}
              options={['4096', '8192', '16384', '32768', '65536']}
              onChange={(event) => section.update({ num_ctx: Number(event.target.value) })}
            />
          </FormField>
          <FormField
            id={`${ids}-tools`}
            label="Tool loop: steps per round"
            hint="How often the agent may call tools before it must answer."
          >
            <TextInput
              id={`${ids}-tools`}
              type="number"
              min={1}
              max={20}
              value={String(assistant.max_tool_iterations)}
              onChange={(event) => section.update({ max_tool_iterations: Number(event.target.value) })}
            />
          </FormField>
          <FormField
            id={`${ids}-revisions`}
            label="Reflection loop: revisions"
            hint="How often failed checks are sent back for a rewrite."
          >
            <TextInput
              id={`${ids}-revisions`}
              type="number"
              min={0}
              max={5}
              value={String(assistant.max_revisions)}
              onChange={(event) => section.update({ max_revisions: Number(event.target.value) })}
            />
          </FormField>
          <FormField id={`${ids}-history`} label="Conversation memory (messages)">
            <TextInput
              id={`${ids}-history`}
              type="number"
              min={0}
              max={40}
              value={String(assistant.history_turns)}
              onChange={(event) => section.update({ history_turns: Number(event.target.value) })}
            />
          </FormField>
        </div>
        <div className="grid grid-cols-1 gap-x-8 gap-y-1 sm:grid-cols-2">
          <Toggle
            label="Reflection (fact-check answers)"
            description="Checks numbers, trial IDs and disclosed caveats against the tool results."
            checked={assistant.enable_reflection}
            onChange={(enable_reflection) => section.update({ enable_reflection })}
          />
          <Toggle
            label="Thinking mode"
            description="Qwen reasons before answering: better on hard questions, much slower on CPU."
            checked={assistant.think}
            onChange={(think) => section.update({ think })}
          />
          <Toggle
            label="Offline fallback"
            description="If Ollama or the model is unavailable, answer with the rule-based planner."
            checked={assistant.offline_fallback}
            onChange={(offline_fallback) => section.update({ offline_fallback })}
          />
          <Toggle
            label="Always use the offline planner"
            description="Skips Ollama entirely – handy for presentations on a laptop without a GPU."
            checked={assistant.force_offline}
            onChange={(force_offline) => section.update({ force_offline })}
          />
        </div>
        <FormField
          id={`${ids}-instructions`}
          label="Extra instructions for the model"
          hint="Added to the system prompt, e.g. house style or audience."
        >
          <TextArea
            id={`${ids}-instructions`}
            rows={3}
            value={assistant.extra_instructions}
            onChange={(event) => section.update({ extra_instructions: event.target.value })}
          />
        </FormField>
        <FormField
          id={`${ids}-questions`}
          label="Suggested questions (one per line)"
          hint="Shown as one-click chips when a conversation starts."
        >
          <TextArea
            id={`${ids}-questions`}
            rows={5}
            value={assistant.suggested_questions.join('\n')}
            onChange={(event) =>
              section.update({
                suggested_questions: event.target.value.split('\n').map((line) => line.trimStart()),
              })
            }
            onBlur={() =>
              section.update({
                suggested_questions: assistant.suggested_questions.map((line) => line.trim()).filter(Boolean),
              })
            }
          />
        </FormField>
      </Card>

      <Card
        title="How the agent works"
        description="LangGraph state machine shared by Qwen 3.6 and the offline planner."
      >
        <AgentLoopDiagram
          maxToolIterations={assistant.max_tool_iterations}
          maxRevisions={assistant.max_revisions}
          reflection={assistant.enable_reflection}
        />
        <GraphSource />
      </Card>
    </>
  );
};
